# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/Projects/Bricks_6/project_1.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/Projects/Bricks_6/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files D:/Xilinx/MATLAB/ANUPimage2coe/GameOver.coe
read_vhdl -library xil_defaultlib {
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/V_SYNC.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/H_SYNC.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/CLK_DELAY.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/LCD.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/Block_1.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/BLOCK_2.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/BALL.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/DEFENSE.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/MOVE_X_DIRECTION.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/move_delay.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/MOVE_Y_DIRECTION.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/FSM_GAME.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/X_BOUNCE_CHECK.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/MOVE_BAR.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/imports/Xilinx/kcpsm6.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/TOUCH_POSITIONS.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/imports/new/TOUCHES_ASM_V7.vhd
  D:/Xilinx/Projects/Bricks_6/project_1.srcs/sources_1/new/MOVE_TOUCHES.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilinx/Projects/Bricks_6/project_1.srcs/constrs_1/new/screen_IO.xdc
set_property used_in_implementation false [get_files D:/Xilinx/Projects/Bricks_6/project_1.srcs/constrs_1/new/screen_IO.xdc]


synth_design -top LCD -part xc7z010clg400-3


write_checkpoint -force -noxdef LCD.dcp

catch { report_utilization -file LCD_utilization_synth.rpt -pb LCD_utilization_synth.pb }
